### ISSUE TITLE
bucket not found when attempting to use template

### ISSUE THREAD

**Issue by RichBrumpton** [rubrikinc/use-case-aws-cloudformation-template-cloudout-s3#16]
**What happened**:

Got "bucket not found" error while following quick-start using URL: https://s3-us-west-1.amazonaws.com/cloudformation-templates-rubrik-prod/rubrik_cloudout.template

**What you expected to happen**:

Being able to use CloudFormation

**How to reproduce it (as minimally and precisely as possible)**:

put https://s3-us-west-1.amazonaws.com/cloudformation-templates-rubrik-prod/rubrik_cloudout.template in browser

**Anything else we need to know?**:

**Comment by DamaniN** [comment]
Fixed by commit 99df63863838929a34911ee665d1fc96ddf3f2e3

**Comment by Dr-Django** [comment]
@DamaniN 

`https://s3-eu-west-1.amazonaws.com/aws.kurento.org/KMS-Coturn-cfn-7.1.0.yaml`


I am trying to create stack for kurento by using cloud-formation aws. But this is no more valid and getting error not found.

What should be the default template for kurento media server. 

I am unable to find any other default template for cloud-formation ? 

It would be awesome, if you help me out here 

Thanks!

**Comment by DamaniN** [comment]
@Dr-Django, I think you've posted this on the wrong repo. This repo is related to deploying Rubrik Security Cloud in AWS. You may want to try the [kurento](https://github.com/Kurento/kurento) project instead.
